### ISSUE TITLE
In readme, provide mock up pictures

### ISSUE THREAD

**Issue by tisaconundrum2** [TheCyaniteProject/autocyn#1]
![image](https://user-images.githubusercontent.com/11879769/33630357-4ca57264-d9c4-11e7-987d-0e9662e7399c.png)
![image](https://user-images.githubusercontent.com/11879769/33630365-51d7e852-d9c4-11e7-9cbf-f14928d3747c.png)
![image](https://user-images.githubusercontent.com/11879769/33630425-8e186332-d9c4-11e7-8f37-8c22ced934fd.png)

**Comment by TheCyaniteProject** [comment]
I'll need to figure out how to add images, but yeah.

**Comment by tisaconundrum2** [comment]
![image](https://user-images.githubusercontent.com/11879769/33741611-48169828-db62-11e7-8906-c3fc26fa3620.png)
